baseURL = 'http://gohugo.io/'
languageCode = 'en-us'
theme = "nightfall"

[menu]
  [[menu.header]]
    name = "Post"
    weight = 0
    url = "posts"

[params]
author = "Erkan Zafer Dolgun"
user = "edolgun"
#hostname = "42.fr"

readingTime = true  # Show reading time on post page
published = true  # Show published data on post page

[[params.social]]
key = 0
name = "Github"
url = "https://github.com/eightimerkan"

[[params.social]]
key = 1
name = "Instagram"
url = "https://www.instagram.com/erkanzaferd"

[[params.social]]
key = 2
name = "Linkedin"
url = "https://www.linkedin.com/in/erkanzaferdolgun"

[[params.social]]
key = 3
name = "Email"
url = "mailto:erkan.dolgun2@gmail.com"
